const fs = require('fs');
const file = 'public/scripts/fieldlot-i18n-messages.js';
let txt = fs.readFileSync(file, 'utf8');

const deAdditions = `
			'exchange.quote.wheat': 'Weizen',
			'exchange.quote.corn': 'Mais',
			'exchange.quote.rapeseed': 'Raps',
			'exchange.quote.sunflower': 'Sonnenblume',
			'logistics.transport': 'Transport',
			'logistics.transportDesc': 'Lkw nach Sofia, Varna oder Export.',
			'logistics.warehouse': 'Lagerhäuser',
			'logistics.warehouseDesc': 'Silos und Kühlhäuser - Kapazität.',
			'logistics.tracking': 'Tracking',
			'logistics.trackingDesc': 'Chargenstatus von Verladung bis Übergabe.',
			'ai.prices': 'Marktpreise',
			'ai.pricesDesc': 'Aktuelle Preise und was gehandelt wird.',
			'ai.pricesEx': '„Was kostet Sonnenblumenkern?“',
			'ai.timing': 'Analyse',
			'ai.timingDesc': 'Wann verkaufen und Preisprognosen.',
			'ai.timingEx': '„Gibt es Nachfrage nach Weizen?“',
			'ai.nav': 'Navigation',
			'ai.navDesc': 'Hilfe bei Inseraten, Filtern, Logistik.',
			'ai.navEx': '„Wie inseriere ich Tomaten?“',
			'ai.open': 'KI-Chat öffnen',
			'chat.hint': 'RAG · Kategorien, Kulturen · Foto',
			'chat.imageTooBig': 'Bild ist zu groß (max. ~4 MB).',
			'chat.imageErr': 'Bild konnte nicht geladen werden.',
			'chat.viewCatalog': 'Passende Angebote im Katalog ansehen →',
			'chat.quickDraft': 'Neues Inserat',
			'chat.quickEdit': 'Text bearbeiten',
			'chat.quickBarley': 'Gerste',
			'chat.photoBtn': 'Foto',
			'chat.placeholder': 'Z.B. Wie ist der Weizenpreis?',
			'chat.send': 'Senden',
			'chat.welcome': 'Hallo. Ich bin Fieldlot Guide.',
			'chat.thinking': 'Ich denke nach…',
			'chat.offlinePh': 'Chat ist offline.',
			'chat.offlineReply': 'Chat ist offline.',
			'chat.noReply': 'Keine Antwort.',
			'chat.network': 'Offline.',
			'chat.busy': 'Chat ist beschäftigt.',
			'listing.buy': 'Gesucht',
			'listing.sell': 'Zu verkaufen',
			'listing.connect': 'Kontakt',
			'listing.offer': 'Angebot machen',
			'listing.buyBtn': 'Kaufen',
			'listing.farmerAlt': 'Landwirtprofil',
			'listing.loadFail': 'Fehler beim Laden.',
			'catalog.meta.title': 'Katalog — Fieldlot',
			'catalog.meta.description': 'Live-Agrarinserate von borsaagro.com.',
			'catalog.nav': 'Hauptnavigation',
			'catalog.banner': '<strong>Live-Katalog</strong>',
			'catalog.loading': 'Inserate werden geladen…',
			'catalog.sourceLink': 'Originales Inserat ansehen →',
			'catalog.access': 'Zugang anfragen',
			'catalog.title': 'Angebotskatalog',
			'catalog.lead': 'Durchsuche Live-Inserate nach Kultur.',
			'catalog.filterSearch': 'Suchen',
			'catalog.searchPh': 'Weizen, Sonnenblumen…',
			'catalog.filterCat': 'Kategorie',
			'catalog.filterCrop': 'Kultur',
			'catalog.filterRegion': 'Region',
			'catalog.filterRole': 'Typ',
			'catalog.all': 'Alle',
			'catalog.cat.grain': 'Getreide',
			'catalog.cat.oil': 'Öl',
			'catalog.cat.oilseed': 'Ölsaaten',
			'catalog.cat.canned': 'Konserven',
			'catalog.cat.fertilizer': 'Düngemittel',
			'catalog.cat.machines': 'Maschinen',
			'catalog.cat.feed': 'Futtermittel',
			'catalog.crop.wheat': 'Weizen',
			'catalog.crop.barley': 'Gerste',
			'catalog.crop.corn': 'Mais',
			'catalog.crop.sunflower': 'Sonnenblumen',
			'catalog.crop.rapeseed': 'Raps',
			'catalog.crop.tomato': 'Tomaten',
			'catalog.crop.pepper': 'Paprika',
			'catalog.crop.preserves': 'Konserven',
			'catalog.crop.herbs': 'Kräuter',
			'catalog.crop.tractor': 'Maschinen',
			'catalog.cat.fruit': 'Obst',
			'catalog.cat.veg': 'Gemüse',
			'catalog.region.national': 'Ganz Bulgarien',
			'catalog.region.dobrudzha': 'Dobrudscha',
			'catalog.region.north': 'Norden',
			'catalog.region.south': 'Süden',
			'catalog.region.west': 'Westen',
			'catalog.role.sell': 'Zu verkaufen',
			'catalog.role.buy': 'Gesucht',
			'catalog.reset': 'Zurücksetzen',
			'catalog.offers': 'Angebote',
			'catalog.offerOne': 'Angebot',
			'catalog.sort': 'Sortierung: neuste',
			'catalog.detailOffer': 'Inserat',
			'catalog.detailCta': 'Anfrage',
			'catalog.empty': 'Keine Angebote.',
			'catalog.emptyHint': 'Versuchen Sie eine andere Kombination.',
			'catalog.demo': 'Demo',
			'catalog.loc': 'Ort',
			'catalog.qty': 'Menge',
			'catalog.price': 'Preis',
			'catalog.term': 'Bedingungen',
			'catalog.harvest': 'Ernte / Saison',
			'catalog.quality': 'Qualität',
			'catalog.contact': 'Kontakt',
			'catalog.detailNote': 'Inserat aus einer öffentlichen Quelle.',
			'catalog.footer': '© Fieldlot · Katalog',
			'catalog.footerHome': 'Zurück zur Startseite',
`;

// Insert it right before the end of the de object (},)
txt = txt.replace(/\t\t\},/g, deAdditions + '\t\t},');

fs.writeFileSync(file, txt);
