en: {
			'meta.title': 'Fieldlot — agro marketplace · farmers & buyers',
			'meta.description':
				'Digital agro ecosystem: listings, exchange, logistics and direct deals between farmers and the market in Bulgaria.',
			'lang.label': 'Language',
			'nav.openMenu': 'Open menu',
			'nav.close': 'Close',
			'nav.searchPlaceholder': 'Search tomatoes, oil, wheat…',
			'nav.login': 'Early access',
			'nav.register': 'Apply',
			'nav.publish': 'Post listing',
			'nav.sections': 'Market sections',
			'nav.categories': 'Categories',
			'nav.market': 'Marketplace',
			'nav.exchange': 'Exchange',
			'nav.logistics': 'Logistics',
			'nav.farmers': 'Producers',
			'nav.demoCatalog': 'Catalog',
			'nav.home': 'Home',
			'nav.catalog': 'Catalog',
			'nav.earlyAccess': 'Early access',
			'nav.join': 'Join',
			'hero.badge': 'Digital agro ecosystem · Bulgaria',
			'hero.title': 'Connecting farmers directly to the market.',
			'hero.buy': 'Buy produce',
			'hero.sell': 'Sell produce',
			'hero.ai': 'AI assistant',
			'hero.stat1': 'live listings',
			'hero.stat2': 'field-scale lots',
			'hero.stat3': 'no commission · phase 1',
			'cat.eyebrow': 'Categories',
			'cat.title': 'Your whole farm on one platform',
			'cat.lead': 'From vegetables to machinery — find or post in the right category.',
			'cat.veg': 'Vegetables',
			'cat.vegHint': 'tomatoes, peppers…',
			'cat.fruit': 'Fruit',
			'cat.fruitHint': 'apples, pears…',
			'cat.grain': 'Grain',
			'cat.grainHint': 'wheat, corn…',
			'cat.oil': 'Oil',
			'cat.oilHint': 'bottles, sunflower…',
			'cat.canned': 'Canned goods',
			'cat.cannedHint': 'processing',
			'cat.fertilizer': 'Fertilizer',
			'cat.fertilizerHint': 'farm inputs',
			'cat.machines': 'Machinery',
			'cat.machinesHint': 'equipment',
			'cat.feed': 'Feed',
			'cat.feedHint': 'hay, feed',
			'listings.eyebrow': 'Marketplace',
			'listings.title': 'Active listings',
			'listings.lead':
				'Cards like a modern B2B market — volume, region, price and direct contact.',
			'listings.demoStrip':
				'Listings from borsaagro.com · full <a href="/catalog.html">catalog</a>',
			'farmers.eyebrow': 'Producers',
			'farmers.title': 'Top farmers on the platform',
			'farmers.lead': 'Farm, field or facility — see who you deal with.',
			'farmers.badge': 'Available slot',
			'farmers.slotFarm': 'Your farm could be here',
			'farmers.slotField': 'Your farm operation could be here',
			'farmers.slotFacility': 'Your warehouse or plant could be here',
			'farmers.cta': 'Publish your profile (early access)',
			'exchange.eyebrow': 'Exchange',
			'exchange.title': 'Live market prices',
			'exchange.lead':
				'Indicative MATIF prices (borsaagro.com) in BGN/ton — guidance, not a trade offer.',
			'exchange.live': 'LIVE · exchange',
			'exchange.updatedNow': 'updated just now',
			'exchange.updated': 'updated',
			'exchange.colProduct': 'Product',
			'exchange.colPrice': 'Price today',
			'exchange.colChange': 'Change',
			'exchange.fail': 'Exchange prices are temporarily unavailable. Try again later.',
			'logistics.eyebrow': 'Logistics',
			'logistics.title': 'From field to warehouse or buyer',
			'logistics.lead':
				'Trucks, warehouses, cold storage and tracking — integrated in the ecosystem.',
			'logistics.transport': 'Transport',
			'logistics.transportDesc':
				'Find a truck to Sofia, Varna or an export hub. Deal directly with the carrier.',
			'logistics.warehouse': 'Warehouses',
			'logistics.warehouseDesc':
				'Silos, cold stores and logistics hubs — visibility on stock and capacity.',
			'logistics.tracking': 'Tracking',
			'logistics.trackingDesc':
				'Batch status from loading to handover — fewer surprises in the deal.',
			'logistics.cta': 'Find transport (early access)',
			'spotlight.eyebrow': 'Producers',
			'spotlight.title': 'Trusted farmer profile',
			'spotlight.lead':
				'Photos, certificates, history, rating and farm video — buyers see who they work with.',
			'spotlight.cert': '✓ Certificates',
			'spotlight.gallery': '📷 Gallery',
			'spotlight.rating': '⭐ Rating',
			'spotlight.video': '🎥 Video',
			'spotlight.profile': 'Create profile',
			'spotlight.offers': 'View demo offers',
			'ai.eyebrow': 'AI',
			'ai.title': 'Fieldlot Guide — your agro assistant',
			'ai.lead': 'RAG assistant with access to the catalog and platform rules.',
			'ai.prices': 'Market prices',
			'ai.pricesDesc': 'Quick answers on current levels and what is trading now.',
			'ai.pricesEx': '"What is sunflower worth right now?"',
			'ai.timing': 'Analysis & sell timing',
			'ai.timingDesc': 'When to sell, price outlook and seasonal context (informational).',
			'ai.timingEx': '"Is there demand for wheat in Dobrudzha?"',
			'ai.nav': 'Navigation',
			'ai.navDesc': 'Help with listings, filters, logistics and early access.',
			'ai.navEx': '"How do I post a batch of tomatoes?"',
			'ai.open': 'Open AI chat',
			'cta.eyebrow': 'Early access',
			'cta.title': 'Join the first wave of the platform',
			'cta.lead':
				'Farmers, buyers and logistics — we are building the digital agro ecosystem for Bulgaria and the region.',
			'form.name': 'Full name *',
			'form.email': 'Email *',
			'form.company': 'Company / farm',
			'form.phone': 'Phone',
			'form.phonePh': '+359…',
			'form.role': 'Role / interest',
			'form.rolePh': 'Producer, buyer, logistics…',
			'form.alerts': 'Notify me when the platform launches',
			'form.submit': 'Submit request',
			'form.fine':
				'Demo phase · no commission · no escrow. Not legal or financial advice.',
			'footer.line1': '© Fieldlot · Digital agro ecosystem · Bulgaria',
			'footer.line2': 'Contact:',
			'footer.catalog': 'Catalog',
			'chat.hint': 'RAG · categories, crops · upload a photo',
			'chat.imageTooBig': 'Image is too large (max. ~4 MB).',
			'chat.imageErr': 'Could not load the image.',
			'chat.viewCatalog': 'View matching listings →',
			'chat.quickDraft': 'New listing',
			'chat.quickEdit': 'Edit text',
			'chat.quickBarley': 'Barley',
			'chat.photoBtn': 'Photo',
			'chat.placeholder': 'E.g. What is the wheat price?',
			'chat.send': 'Send',
			'chat.welcome':
				'Hello. I am Fieldlot Guide — an AI agent with RAG and actions: I can check exchange prices, search the catalog, email the team, or register early access (with your details). Ask what you need.',
			'chat.thinking': 'Thinking…',
			'chat.offlinePh': 'Chat is offline in preview — run backend or Vercel.',
			'chat.offlineReply':
				'Chat is offline in this preview (Lovable/static). Catalog at /catalog.html works. For AI — run npm run dev or deploy to Vercel with API.',
			'chat.noReply': 'No reply.',
			'chat.network': 'Offline — /api/fieldlot-chat is not available in preview.',
			'chat.busy': 'Chat is temporarily unavailable.',
			'listing.buy': 'Wanted',
			'listing.sell': 'For sale',
			'listing.connect': 'Contact',
			'listing.offer': 'Make offer',
			'listing.buyBtn': 'Buy',
			'listing.farmerAlt': 'Trusted farmer profile',
			'listing.loadFail':
				'Catalog loads from the <a href="/catalog.html">demo page</a>.',
			'api.banner':
				'<strong>Preview without backend</strong> · Catalog works at <a href="/catalog.html">/catalog.html</a>. Form and AI chat are <em>offline</em> until API is deployed (Vercel / local).',
			'lead.wait': 'Wait 2 seconds.',
			'lead.rate': 'Too many requests.',
			'lead.email': 'Invalid email.',
			'lead.phone': 'Phone +359… or leave empty.',
			'lead.err': 'Error.',
			'lead.offline':
				'Offline — API not available in this preview. Email info@agrinexus.eu or run locally/Vercel.',
			'lead.preview': 'Form is offline in preview. Email: info@agrinexus.eu',
			'lead.waitShort': 'Wait 2 sec.',
			'lead.sending': 'Sending…',
			'lead.okMail': 'Done — we sent a notification.',
			'lead.ok': 'Request saved.',
			'lead.offlineApi': 'Offline — API unavailable. info@agrinexus.eu',
			'catalog.meta.title': 'Catalog — Fieldlot',
			'catalog.meta.description':
				'Live agro listings from borsaagro.com — Fieldlot B2B marketplace.',
			'catalog.nav': 'Main navigation',
			'catalog.banner':
				'<strong>Live catalog</strong> — listings from borsaagro.com, sorted by date. Crop photos; see source for the original.',
			'catalog.loading': 'Loading listings…',
			'catalog.sourceLink': 'View original listing on borsaagro.com →',
			'catalog.access': 'Request access',
			'catalog.title': 'Offers catalog',
			'catalog.lead':
				'Browse live listings by crop, region and type (sale or wanted). Filter, open details and follow the source link.',
			'catalog.filterSearch': 'Search',
			'catalog.searchPh': 'wheat, Dobrudzha, sunflower…',
			'catalog.filterCat': 'Category',
			'catalog.filterCrop': 'Crop',
			'catalog.filterRegion': 'Region',
			'catalog.filterRole': 'Type',
			'catalog.all': 'All',
			'catalog.cat.grain': 'Grain',
			'catalog.cat.oil': 'Oil / oilseeds',
			'catalog.cat.oilseed': 'Oilseeds',
			'catalog.cat.canned': 'Canned goods',
			'catalog.cat.fertilizer': 'Fertilizer',
			'catalog.cat.machines': 'Machinery',
			'catalog.cat.feed': 'Feed',
			'catalog.crop.wheat': 'Wheat',
			'catalog.crop.barley': 'Barley',
			'catalog.crop.corn': 'Corn',
			'catalog.crop.sunflower': 'Sunflower',
			'catalog.crop.rapeseed': 'Rapeseed',
			'catalog.crop.tomato': 'Tomatoes',
			'catalog.crop.pepper': 'Peppers',
			'catalog.crop.preserves': 'Preserves',
			'catalog.crop.herbs': 'Herbs',
			'catalog.crop.tractor': 'Machinery',
			'catalog.cat.fruit': 'Fruit',
			'catalog.cat.veg': 'Vegetables',
			'catalog.region.national': 'All Bulgaria',
			'catalog.region.dobrudzha': 'Dobrudzha',
			'catalog.region.north': 'North',
			'catalog.region.south': 'South',
			'catalog.region.west': 'West',
			'catalog.role.sell': 'For sale',
			'catalog.role.buy': 'Wanted',
			'catalog.reset': 'Clear',
			'catalog.offers': 'offers',
			'catalog.offerOne': 'offer',
			'catalog.sort': 'Sort: newest',
			'catalog.detailOffer': 'Listing',
			'catalog.detailCta': 'Inquiry (early access)',
			'catalog.empty': 'No offers for the selected filters.',
			'catalog.emptyHint':
				'Try another combination or <a href="/#cta">request early access</a>.',
			'catalog.demo': 'Demo',
			'catalog.loc': 'Location',
			'catalog.qty': 'Quantity',
			'catalog.price': 'Price',
			'catalog.term': 'Terms',
			'catalog.harvest': 'Harvest / season',
			'catalog.quality': 'Quality',
			'catalog.contact': 'Contact',
			'catalog.detailNote':
				'Listing from a public source. Contact the lister on borsaagro.com or send an inquiry via Fieldlot.',
			'catalog.footer': '© Fieldlot · Catalog',
			'catalog.footerHome': 'Back to home',
			'catalog.downloadPdf': 'Download PDF',
			'catalog.pdfLoading': 'Generating…',
			'catalog.pdfErr': 'Could not generate PDF. Check network or try again.',
			'catalog.pdfUnavailable': 'PDF module not loaded.',
		},